//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIDS.API.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class H_KIDSEntities : DbContext
    {
        public H_KIDSEntities()
            : base("name=H_KIDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_Login_Result> sp_Login(string nickName, string password)
        {
            var nickNameParameter = nickName != null ?
                new ObjectParameter("NickName", nickName) :
                new ObjectParameter("NickName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Login_Result>("sp_Login", nickNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_Student_Prescription_sel_Result> sp_Student_Prescription_sel(Nullable<System.Guid> studentID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Student_Prescription_sel_Result>("sp_Student_Prescription_sel", studentIDParameter);
        }
    
        public virtual ObjectResult<sp_Teacher_Application_sel_Result> sp_Teacher_Application_sel(Nullable<System.Guid> classID, Nullable<System.Guid> teacherID)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(System.Guid));
    
            var teacherIDParameter = teacherID.HasValue ?
                new ObjectParameter("TeacherID", teacherID) :
                new ObjectParameter("TeacherID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Teacher_Application_sel_Result>("sp_Teacher_Application_sel", classIDParameter, teacherIDParameter);
        }
    
        public virtual ObjectResult<sp_Teacher_Attendance_Count_sel_Result> sp_Teacher_Attendance_Count_sel(Nullable<System.Guid> classID, Nullable<System.DateTime> date)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(System.Guid));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Teacher_Attendance_Count_sel_Result>("sp_Teacher_Attendance_Count_sel", classIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<sp_Teacher_Attendance_sel_Result> sp_Teacher_Attendance_sel(Nullable<System.Guid> classID, Nullable<System.DateTime> date)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(System.Guid));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Teacher_Attendance_sel_Result>("sp_Teacher_Attendance_sel", classIDParameter, dateParameter);
        }
    
        public virtual ObjectResult<sp_Teacher_Prescription_sel_Result> sp_Teacher_Prescription_sel(Nullable<System.Guid> classID, Nullable<System.Guid> teacherID)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(System.Guid));
    
            var teacherIDParameter = teacherID.HasValue ?
                new ObjectParameter("TeacherID", teacherID) :
                new ObjectParameter("TeacherID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Teacher_Prescription_sel_Result>("sp_Teacher_Prescription_sel", classIDParameter, teacherIDParameter);
        }
    
        public virtual ObjectResult<sp_Teacher_Prescription_Detail_sel_Result> sp_Teacher_Prescription_Detail_sel(Nullable<System.Guid> prescriptionID)
        {
            var prescriptionIDParameter = prescriptionID.HasValue ?
                new ObjectParameter("PrescriptionID", prescriptionID) :
                new ObjectParameter("PrescriptionID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Teacher_Prescription_Detail_sel_Result>("sp_Teacher_Prescription_Detail_sel", prescriptionIDParameter);
        }
    }
}
